import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";
import Skeleton from "@material-ui/lab/Skeleton";

//graphql
import { GET_HOTELS } from "../../../graphql/hotel/getHotels";
import { useQuery } from "@apollo/client";

export default function ManageHotel() {
  const { loading, error, data } = useQuery(GET_HOTELS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;
  console.log(data.getHotels);

  const result = data.getHotels.map((value, idx) => {
    return (
      <TableRow className="list-item" key={idx}>
        <TableCell>{idx}</TableCell>
        <TableCell align="center">{value.nameHotel}</TableCell>
        <TableCell align="center">
          {/* <img className="img" src={value.imgHotel} /> */}
          <Skeleton variant="rect" width={210} height={118} />
        </TableCell>
        <TableCell align="center">{value.rate} sao</TableCell>
        <TableCell className="item-status" align="center">
          {value.checkIn}
        </TableCell>
        <TableCell align="center">{value.checkOut}</TableCell>
        <TableCell align="center">{value.impress}</TableCell>
        <TableCell align="center">
          <div className="entry-btn">
            <IconButton>
              <i className="fas fa-edit"></i>
            </IconButton>
            <IconButton>
              <i className="fas fa-trash-alt"></i>
            </IconButton>
          </div>
        </TableCell>
      </TableRow>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý phòng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="entry">
        <h2 className="title">Quản lý khách sạn</h2>

        <TableContainer component={Paper}>
          <Table aria-label="simple table">
            <TableHead>
              <TableRow className="table-row">
                <TableCell>STT</TableCell>
                <TableCell>Khách sạn</TableCell>
                <TableCell align="center">Hình ảnh</TableCell>
                <TableCell align="center">Đánh giá</TableCell>
                <TableCell align="center">Thời gian nhận phòng</TableCell>
                <TableCell align="center">Thời gian trả phòng</TableCell>
                <TableCell align="center">Ấn tượng</TableCell>
                <TableCell align="center"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
