import Head from "next/head";
import MainLayout from "../../components/layout/mainLayout";

export default function Admin() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="admin">
        <h2>Nothing here</h2>
      </div>
    </MainLayout>
  );
}
