import { Box } from "@material-ui/core";
import Head from "next/head";
import MainLayout from "../../components/layout/mainLayout";

export default function Admin() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="admin">
        <Box
          style={{ marginLeft: "300px", marginTop: "150px", display: "flex" }}
          className="tabs-menu"
        >
          <h2>Comming soon </h2>
          <div className="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </Box>
      </div>
    </MainLayout>
  );
}
