import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Contents from "../../components/layout/contents";
import Entry from "../../components/layout/entrys";
import MainLayout from "../../components/layout/mainLayout";

export default function ManageUser() {
  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý người dùng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="entry">
        <h2 className="title">Quản lý người dùng</h2>

        <TableContainer component={Paper}>
          <Table aria-label="simple table">
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Họ và tên</TableCell>
                <TableCell align="center">Hình ảnh</TableCell>
                <TableCell align="center">Số điện thoại</TableCell>
                <TableCell align="center">CMND</TableCell>
                <TableCell align="center">Email</TableCell>
                <TableCell align="center">Vai trò</TableCell>
                <TableCell align="center">Ví tiền</TableCell>
                <TableCell align="center"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              <TableRow className="list-item">
                <TableCell align="center">1</TableCell>
                <TableCell align="center">Đỗ Phạm Duy</TableCell>
                <TableCell align="center">
                  <img src="#" />
                </TableCell>
                <TableCell align="center">012312312</TableCell>
                <TableCell align="center">012345678</TableCell>
                <TableCell align="center">duy@gmail.com</TableCell>
                <TableCell align="center">Khách hàng</TableCell>
                <TableCell align="center">9999999 VNĐ</TableCell>
                <TableCell align="center">
                  <div className="entry-btn">
                    <IconButton>
                      <i className="fas fa-edit"></i>
                    </IconButton>
                    <IconButton>
                      <i className="fas fa-trash-alt"></i>
                    </IconButton>
                  </div>
                </TableCell>
              </TableRow>

              <TableRow className="list-item">
                <TableCell align="center">1</TableCell>
                <TableCell align="center">Đỗ Phạm Duy</TableCell>
                <TableCell align="center">
                  <img src="#" />
                </TableCell>
                <TableCell align="center">012312312</TableCell>
                <TableCell align="center">012345678</TableCell>
                <TableCell align="center">duy@gmail.com</TableCell>
                <TableCell align="center">Khách hàng</TableCell>
                <TableCell align="center">9999999 VNĐ</TableCell>
                <TableCell align="center">
                  <div className="entry-btn">
                    <IconButton>
                      <i className="fas fa-edit"></i>
                    </IconButton>
                    <IconButton>
                      <i className="fas fa-trash-alt"></i>
                    </IconButton>
                  </div>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
