import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import MainLayout from "../../components/layout/mainLayout";
import Loading from "../../components/Loading/index";

// graphql
import { GET_USERS } from "../../graphql/customer/getUsers";
import { useQuery } from "@apollo/client";
import BtnDecentralization from "../../components/manageUser/btnDecentralization";

export default function ManageDecentralization() {
  const { loading, error, data } = useQuery(GET_USERS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;

  const result = data.getUsers.map((value, idx) => {
    return (
      <TableRow className="list-item">
        <TableCell align="center">{idx}</TableCell>
        <TableCell align="center">{value.name}</TableCell>
        <TableCell align="center">{value.email}</TableCell>
        <TableCell align="center">
          {value.role === true ? "Admin" : "Khách hàng"}
        </TableCell>
        <TableCell align="center">
          <BtnDecentralization userID={value.id} />
        </TableCell>
      </TableRow>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý người dùng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <div className="entry">
        <h2 className="title animate__animated animate__fadeInDown">
          Phân quyền thành viên
        </h2>

        <TableContainer component={Paper}>
          <Table
            className="animate__animated animate__bounceInUp"
            aria-label="simple table"
          >
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Họ và tên</TableCell>
                <TableCell align="center">Email</TableCell>
                <TableCell align="center">Quyền</TableCell>
                <TableCell align="center"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
