import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";

//graphql
import { GET_PAYMENTS } from "../../../graphql/payment/payment";
import { useQuery } from "@apollo/client";

export default function ManageRevenue() {
  const { loading, error, data } = useQuery(GET_PAYMENTS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;

  const result = data.getPayments.map((value, idx) => {
    const revenue = 0;
    const result = revenue + value.total;
    return result;
  });

  console.log(result);

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý lịch sử thanh toán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <div className="entry">
        <h2 className="title  animate__animated animate__fadeInDown">
          Quản lý lịch sử thanh toán
        </h2>

        <TableContainer component={Paper}>
          <Table
            className="animate__animated animate__bounceInUp"
            aria-label="simple table"
          >
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Họ và tên</TableCell>
                <TableCell align="center">Email</TableCell>
                <TableCell align="center">Mã phiếu đặt phòng</TableCell>
                <TableCell align="center">Mã giảm giá</TableCell>
                <TableCell align="center">Phương thức thanh toán</TableCell>
                <TableCell align="center">Thời gian khởi tạo</TableCell>
                <TableCell align="center">Tổng tiền</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
