import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Head from "next/head";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";

//graphql
import { GET_BILLS } from "../../../graphql/payment/bill";
import { useQuery } from "@apollo/client";

export default function ManageBill() {
  const { loading, error, data } = useQuery(GET_BILLS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;

  const result = data.getBills.map((value, idx) => {
    return (
      <TableRow className="list-item" key={idx}>
        <TableCell>{idx}</TableCell>
        <TableCell align="center">{value.nameUser}</TableCell>
        <TableCell align="center">{value.email}</TableCell>
        <TableCell align="center">{value.phoneNumber}</TableCell>
        <TableCell align="center">{value.CMND}</TableCell>
        <TableCell align="center">{value.hotel}</TableCell>
        <TableCell align="center">{value.room}</TableCell>
        <TableCell align="center">{value.bed}</TableCell>
        <TableCell align="center">{value.bookingDate}</TableCell>
        <TableCell align="center">
          {value.codeVoucher ? value.codeVoucher : "..."}
        </TableCell>
        <TableCell align="center">
          - {value.moneyDecreased.toLocaleString()} vnđ
        </TableCell>
        <TableCell align="center">{value.total.toLocaleString()} vnđ</TableCell>
      </TableRow>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý hóa đơn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <div className="entry">
        <h2 className="title animate__animated animate__fadeInDown">
          Quản lý hóa đơn
        </h2>

        <TableContainer component={Paper}>
          <Table
            className="animate__animated animate__bounceInUp"
            aria-label="simple table"
          >
            <TableHead>
              <TableRow className="table-row">
                <TableCell>STT</TableCell>
                <TableCell align="center">Họ và tên</TableCell>
                <TableCell align="center">Email</TableCell>
                <TableCell align="center">SĐT</TableCell>
                <TableCell align="center">CMND</TableCell>
                <TableCell align="center">Khách sạn</TableCell>
                <TableCell align="center">Phòng</TableCell>
                <TableCell align="center">Giường</TableCell>
                <TableCell align="center">Ngày đặt</TableCell>
                <TableCell align="center">Mã giảm giá</TableCell>
                <TableCell align="center">Tiền giảm</TableCell>
                <TableCell align="center">Tổng cộng</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
