import Head from "next/head";
import {
  Box,
  Button,
  IconButton,
  Paper,
  Switch,
  TextField,
} from "@material-ui/core";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import SimpleDialog from "../../../components/manageRoom/updateRoom";

//  toast
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// graphql
import { GET_ROOM } from "../../../graphql/room/getRoom";
import { useQuery } from "@apollo/client";
import { useRouter } from "next/dist/client/router";
import FormUpdateRoom from "../../../components/manageRoom/updateRoom";

export default function ManageRoom() {
  const router = useRouter();
  const { updateRoomID } = router.query;

  const { loading, error, data } = useQuery(GET_ROOM, {
    variables: {
      id: updateRoomID,
    },
    skip: updateRoomID === null,
  });

  if (loading) return <Loading />;
  if (error) return <h2>Error</h2>;

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý phòng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FormUpdateRoom dataRoom={data.getRoom} updateRoomID={updateRoomID} />
    </MainLayout>
  );
}
