import Head from "next/head";
import {
  Button,
  IconButton,
  Link,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import { AddCircle } from "@material-ui/icons";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";
import DialogAddRoom from "../../../components/manageRoom/DialogAddRoom";

// graphql
import { GET_ROOMS } from "../../../graphql/room/getRooms";
import { useQuery } from "@apollo/client";
import { useState } from "react";
import DeleteRoom from "../../../components/room/deleteRoom";

export default function ManageRoom() {
  const [open, setOpen] = useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleClose = (value) => {
    setOpen(false);
  };

  const { loading, error, data } = useQuery(GET_ROOMS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;

  const result = data.getRooms.map((value, idx) => {
    return (
      <>
        <TableRow key={idx} className="list-item">
          <TableCell align="center">{idx}</TableCell>
          <TableCell align="center">{value.hotel}</TableCell>
          <TableCell align="center">{value.numberRoom}</TableCell>
          <TableCell align="center">{value.amountOfPeople}</TableCell>
          <TableCell
            className={true ? "item-status-true" : "item-status-false"}
            align="center"
          >
            <b>{value.status ? "Đã đặt" : "Còn trống"}</b>
          </TableCell>
          <TableCell align="center">{value.sizeRoom}</TableCell>
          <TableCell align="center">{value.bed}</TableCell>
          <TableCell align="center">{value.quality}</TableCell>
          <TableCell align="center">
            {value.price.toLocaleString()} VNĐ
          </TableCell>
          <TableCell align="center">{value.createAt}</TableCell>
          <TableCell align="center">
            {value.updateAt ? moment(value.updateAt).fromNow(true) : "Chưa có"}
          </TableCell>
          <TableCell align="center">
            <div className="entry-btn">
              <IconButton onClick={handleClickOpen}>
                <Link href={`/admin/manageRoom/${value.id}`}>
                  <i className="fas fa-edit"></i>
                </Link>
              </IconButton>
              <DeleteRoom roomID={value.id} />
            </div>
          </TableCell>
        </TableRow>
      </>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý phòng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <div className="entry">
        <h2 className="title animate__animated animate__fadeInDown">
          Quản lý phòng
        </h2>
        <IconButton onClick={handleClickOpen}>
          <AddCircle />
        </IconButton>
        <DialogAddRoom open={open} onClose={handleClose} />
        <TableContainer component={Paper}>
          <Table
            className="animate__animated animate__bounceInUp"
            aria-label="simple table"
          >
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Khách sạn</TableCell>
                <TableCell align="center">Mã phòng</TableCell>
                <TableCell align="center">Số người</TableCell>
                <TableCell align="center">Trạng thái</TableCell>
                <TableCell align="center">Kích thước phòng</TableCell>
                <TableCell align="center">Giường</TableCell>
                <TableCell align="center">Chất lượng phòng</TableCell>
                <TableCell align="center">Giá</TableCell>
                <TableCell align="center">Ngày khởi tạo</TableCell>
                <TableCell align="center">Thòi gian cập nhật</TableCell>
                <TableCell align="center"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
