import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";

// graphql
import { GET_ORDER_DETAILS } from "../../../graphql/payment/orderDetail";
import { useQuery } from "@apollo/client";
import DeleteOrderDetail from "../../../components/manageBooking/deleteBooking";

export default function manageBooking() {
  const { loading, error, data } = useQuery(GET_ORDER_DETAILS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;
  console.log(data);

  const result = data.getOrderDetails.map((value, idx) => {
    return (
      <TableRow key={idx} className="list-item">
        <TableCell align="center">{idx}</TableCell>
        <TableCell align="center">{value.hotel}</TableCell>
        <TableCell align="center">{value.numberRoom}</TableCell>
        <TableCell align="center">{value.amountOfPeople}</TableCell>
        <TableCell
          className={value.status ? "item-status-true" : "item-status-false"}
          align="center"
        >
          <b>{value.status === true ? "Đã đặt" : "Trống"}</b>
        </TableCell>
        <TableCell align="center">{value.sizeRoom}</TableCell>
        <TableCell align="center">{value.bed}</TableCell>
        <TableCell align="center">{value.price} VNĐ</TableCell>
        <TableCell align="center">{value.quality}</TableCell>
        <TableCell
          className={
            value.isCheckout ? "item-status-true" : "item-status-false"
          }
          align="center"
        >
          <b>
            {value.isCheckout === true ? "Đã thanh toán" : "Chưa thanh toán"}
          </b>
        </TableCell>
        <TableCell align="center">
          {moment(value.createAt).fromNow(true)}
        </TableCell>
        <TableCell align="center">{value.total} VNĐ</TableCell>
        <TableCell align="center">
          <div className="entry-btn">
            {value.isCheckout ? (
              ""
            ) : (
              <DeleteOrderDetail orderDetailID={value.id} />
            )}
          </div>
        </TableCell>
      </TableRow>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý đặt phòng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <div className="entry">
        <h2 className="title animate__animated animate__fadeInDown">
          Quản lý đặt phòng
        </h2>

        <TableContainer component={Paper}>
          <Table
            className="animate__animated animate__bounceInUp"
            aria-label="simple table"
          >
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Khách sạn</TableCell>
                <TableCell align="center">Mã phòng</TableCell>
                <TableCell align="center">Số người</TableCell>
                <TableCell align="center">Trạng thái</TableCell>
                <TableCell align="center">Kích thước phòng</TableCell>
                <TableCell align="center">Giường</TableCell>
                <TableCell align="center">Giá</TableCell>
                <TableCell align="center">Chất lượng phòng</TableCell>
                <TableCell align="center">Trạng thái thanh toán</TableCell>
                <TableCell align="center">Thời gian khởi tạo</TableCell>
                <TableCell align="center">Tổng</TableCell>
                <TableCell align="center"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
