import Head from "next/head";
import {
  Button,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@material-ui/core";
import Contents from "../../../components/layout/contents";
import Entry from "../../../components/layout/entrys";
import MainLayout from "../../../components/layout/mainLayout";
import Loading from "../../../components/Loading/index";
import moment from "moment";
import "moment/locale/vi";

//graphql
import { GET_PAYMENTS } from "../../../graphql/payment/payment";
import { useQuery } from "@apollo/client";

export default function ManageHistoryPayment() {
  const { loading, error, data } = useQuery(GET_PAYMENTS);

  if (loading) return <Loading />;
  if (error || !data) return <h2>Error</h2>;

  const result = data.getPayments.map((value, idx) => {
    return (
      <TableRow className="list-item">
        <TableCell align="center">{idx}</TableCell>
        <TableCell align="center">{value.email}</TableCell>
        <TableCell align="center">{value.orderDetail}</TableCell>
        <TableCell className="item-status-true" align="center">
          <b>{value.paymentMethod}</b>
        </TableCell>
        <TableCell align="center">{value.createAt}</TableCell>
        <TableCell align="center">
          {value.checkout.toLocaleString()} VNĐ
        </TableCell>
      </TableRow>
    );
  });

  return (
    <MainLayout>
      <Head>
        <title>dinosours - quản lý lịch sử thanh toán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="entry">
        <h2 className="title">Quản lý lịch sử thanh toán</h2>

        <TableContainer component={Paper}>
          <Table aria-label="simple table">
            <TableHead>
              <TableRow className="table-row">
                <TableCell align="center">STT</TableCell>
                <TableCell align="center">Email</TableCell>
                <TableCell align="center">Mã phiếu đặt phòng</TableCell>
                <TableCell align="center">Phương thức thanh toán</TableCell>
                <TableCell align="center">Thời gian khởi tạo</TableCell>
                <TableCell align="center">Tổng tiền</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>{result}</TableBody>
          </Table>
        </TableContainer>
      </div>
    </MainLayout>
  );
}
