import { Box, Button, Checkbox, Paper, TextField } from "@material-ui/core";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import MainLayout from "../components/layout/mainLayout";
import Cookie from "js-cookie";

// graphql
import { LOG_IN } from "../graphql/auth/login";

//  toast
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useState } from "react";
import { useMutation } from "@apollo/client";
import { useForm } from "../util/formHook";

export default function Home() {
  const router = useRouter();
  // const [getCheck, setCheck] = useState({
  //   status: false,
  // });

  // const handelChange = (e) => {
  //   const checked = e.target.checked;
  //   setCheck({
  //     ...getCheck,
  //     [e.target.name]: e.target.value,
  //     status: checked,
  //   });
  // };

  const [errors, setErrors] = useState({});

  const [values, setValues] = useState({
    email: "",
    password: "",
  });

  const ToastSuccess = () => {
    toast.success(`Chào mừng bạn đến với Dinosour.`, {
      position: toast.POSITION.TOP_RIGHT,
      autoClose: 3000,
    });
  };

  const ToastErr = (err) => {
    toast.error(`Email hoặc password sai . Vui lòng thử lại .`, {
      position: toast.POSITION.TOP_RIGHT,
      autoClose: 3000,
    });
  };

  const [adminLogin, { loading, data }] = useMutation(LOG_IN, {
    update(_, result) {
      ToastSuccess();
      Cookie.set("jwtToken", result.data.adminLogin.token);
      router.push("/admin");
    },
    // onCompleted: (data) => {
    //   // Cookie.set('jwtToken',data.)
    //   console.log(data);
    // },
    variables: values,

    onError(err) {
      ToastErr(err);
    },
  });

  const onChange = (e) => {
    setValues({ ...values, [e.target.name]: e.target.value });
  };

  const onSubmit = (e) => {
    e.preventDefault();

    adminLogin();
  };

  return (
    <div className="wrapper">
      <Head>
        <title>Đăng nhập</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      {/* <Checkbox
        onChange={handelChange}
        checked={getCheck.status}
        color="primary"
        inputProps={{ "aria-label": "secondary checkbox" }}
      /> */}
      {/* {Object.keys(errors).length > 0 && ToastErr()} */}
      <ToastContainer />
      <Box className="wrapper__logins animate__animated animate__bounceInUp">
        <Paper>
          <div className="title">
            <h2 className="text">Dinosour.</h2>
          </div>
          <div className="login-form">
            <form className="form" onSubmit={onSubmit}>
              <TextField
                className="field"
                label="Email"
                type="text"
                fullWidth
                name="email"
                variant="outlined"
                value={values.email}
                // error={errors.email ? true : false}
                onChange={onChange}
              />
              <TextField
                className="field"
                label="Mật khẩu"
                fullWidth
                name="password"
                type="password"
                variant="outlined"
                value={values.password}
                // error={errors.password ? true : false}
                onChange={onChange}
              />
              <Button
                className="btn-login"
                type="submit"
                variant="outlined"
                // onClick={() => router.push("/admin")}
              >
                Đăng nhập
              </Button>
            </form>
          </div>
        </Paper>
      </Box>
    </div>
  );
}
